[tool.poetry]
name = "flask-quiz"
version = "0.1.0"
description = ""
authors = ["seisei079"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.0"
gunicorn = "^21.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
